Add an option (enabled by default) to expose all weaviate pods
Includes a new option expose-pods/EXPOSE_PODS which will
port-forward into a specific port all the pods running.
This allows doing specific checks per pod, which would be
impossible when using the load balancer service.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,6 +24,7 @@ jobs:
             weaviate-version: ${{ env.WEAVIATE_VERSION }}
         - name: Check the configured values
           run: |
+            set -ex
             replicas=$(kubectl get sts weaviate -n weaviate -o=jsonpath="{.spec.replicas}")
             if [[ "$replicas" -ne ${{ env.REPLICAS }} ]]; then
                 echo "Error: Replicas count is not equal to ${{ env.REPLICAS }}. Found $replicas"
@@ -57,6 +58,7 @@ jobs:
         WEAVIATE_GRPC_PORT: '50052'
         HELM_BRANCH: 'master'
         ENABLE_BACKUP: 'true'
+        EXPOSE_PODS: 'true'
         VALUES_OVERRIDE: |
           storage:
             size: 50Gi
@@ -80,8 +82,10 @@ jobs:
               enable-backup: ${{ env.ENABLE_BACKUP }}
               values-inline: ${{ env.VALUES_INLINE }}
               observability: 'true'
+              expose-pods: ${{ env.EXPOSE_PODS }}
         - name: Check the configured values
           run: |
+              set -ex
               replicas=$(kubectl get sts weaviate -n weaviate -o=jsonpath="{.spec.replicas}")
               if [[ "$replicas" -ne ${{ env.REPLICAS }} ]]; then
                   echo "Error: Replicas count is not equal to ${{ env.REPLICAS }}. Found $replicas"
@@ -124,6 +128,17 @@ jobs:
                   echo "Error: env.PERSISTENCE_LSM_ACCESS_STRATEGY is not equal to pread. Found $env_value"
                   exit 1
               fi
+              for ((i=0; i<${{ env.REPLICAS }}; i++)); do
+                PORT=$((${{ env.WEAVIATE_PORT }} + i + 1))
+                PROCESS=$(lsof -i :$PORT -sTCP:LISTEN -n -P | grep kubectl-r) || true
+
+                if [ -z "$PROCESS" ]; then
+                  echo "FAIL: Pod $i (Port $PORT): NOT LISTENING"
+                  exit 1
+                else
+                  echo "Pod $i (Port $PORT): LISTENING"
+                fi
+              done
     run-weaviate-local-k8s-which-fails:
       runs-on: ubuntu-latest
       name: Create a single-node Weaviate cluster with non existing image.
@@ -149,6 +164,7 @@ jobs:
             exit 1
         - name: Check that the deployment failed
           run: |
+              set -ex
               availableReplicas=$(kubectl get sts weaviate -n weaviate -o=jsonpath='{.status.availableReplicas}')
               if [[ "$replicas" -ne "0" ]]; then
                   echo "Error: Replicas count should be 0. Found $replicas"
@@ -175,6 +191,7 @@ jobs:
               modules: ${{ env.MODULES }}
         - name: Check the configured values
           run: |
+              set -ex
               replicas=$(kubectl get sts weaviate -n weaviate -o=jsonpath="{.status.availableReplicas}")
               if [[ "$replicas" -ne ${{ env.REPLICAS }} ]]; then
                   echo "Error: Replicas count is not equal to ${{ env.REPLICAS }}. Found $replicas"
@@ -232,6 +249,7 @@ jobs:
             weaviate-version: ${{ env.UPGRADE_VERSION }}
         - name: Check the configured values
           run: |
+            set -ex
             replicas=$(kubectl get sts weaviate -n weaviate -o=jsonpath="{.spec.replicas}")
             if [[ "$replicas" -ne ${{ env.REPLICAS }} ]]; then
                 echo "Error: Replicas count is not equal to ${{ env.REPLICAS }}. Found $replicas"
@@ -254,6 +272,17 @@ jobs:
               echo "Error: Weaviate metrics is not listening, returned $error"
               exit 1
             fi
+            for ((i=0; i<${{ env.REPLICAS }}; i++)); do
+              PORT=$((8080 + i + 1))
+              PROCESS=$(lsof -i :$PORT -sTCP:LISTEN -n -P | grep kubectl-r) || true
+
+              if [ -z "$PROCESS" ]; then
+                echo "FAIL: Pod $i (Port $PORT): NOT LISTENING"
+                exit 1
+              else
+                echo "Pod $i (Port $PORT): LISTENING"
+              fi
+            done
     run-weaviate-local-k8s-raft-upgrade:
       runs-on: ubuntu-latest
       name: Invoke weaviate-local-k8s upgrade to RAFT with basic parameters
@@ -283,6 +312,7 @@ jobs:
             weaviate-version: ${{ env.UPGRADE_VERSION }}
         - name: Check the configured values
           run: |
+            set -ex
             replicas=$(kubectl get sts weaviate -n weaviate -o=jsonpath="{.spec.replicas}")
             if [[ "$replicas" -ne ${{ env.REPLICAS }} ]]; then
                 echo "Error: Replicas count is not equal to ${{ env.REPLICAS }}. Found $replicas"
@@ -325,6 +355,7 @@ jobs:
             weaviate-version: ${{ env.WEAVIATE_VERSION }}
         - name: Check the configured values
           run: |
+            set -ex
             replicas=$(kubectl get sts weaviate -n weaviate -o=jsonpath="{.spec.replicas}")
             if [[ "$replicas" -ne ${{ env.REPLICAS }} ]]; then
                 echo "Error: Replicas count is not equal to ${{ env.REPLICAS }}. Found $replicas"
