Add modules option for the action, it allows enabling some of the ranker/vectorizer modules in the cluster

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -107,4 +107,38 @@ jobs:
                   echo "Error: Replicas count should be 0. Found $replicas"
                   exit 1
               fi
-  
+    run-weaviate-local-k8s-with-module:
+      runs-on: ubuntu-latest
+      name: Invoke weaviate-local-k8s action with text2vec-contextionary module
+      env:
+        WORKERS: '2'
+        REPLICAS: '3'
+        WEAVIATE_VERSION: '1.24.4'
+        MODULES: 'text2vec-contextionary'
+      steps:
+        - id: invoke-local-k8s
+          uses: weaviate/weaviate-local-k8s@main
+          with:
+              workers: ${{ env.WORKERS }}
+              replicas: ${{ env.REPLICAS }}
+              weaviate-version: ${{ env.WEAVIATE_VERSION }}
+              modules: ${{ env.MODULES }}
+        - name: Check the configured values
+          run: |
+              replicas=$(kubectl get sts weaviate -n weaviate -o=jsonpath="{.spec.replicas}")
+              if [[ "$replicas" -ne ${{ env.REPLICAS }} ]]; then
+                  echo "Error: Replicas count is not equal to ${{ env.REPLICAS }}. Found $replicas"
+                  exit 1
+              fi
+              workers=$(kubectl get nodes --selector=node-role.kubernetes.io/control-plane!= --no-headers | wc -l)
+              if [[ "$workers" -ne ${{ env.WORKERS }} ]]; then
+                  echo "Error: Workers count is not equal to ${{ env.WORKERS }}. Found $workers"
+                  exit 1
+              fi
+              versions=$(curl -s http://127.0.0.1:8080}/v1/nodes | jq '.nodes[] | .version' | tr -d '"')
+              for version in `echo $versions | tr '\n' ' '`; do
+                  if [[ "$version" != "${{ env.WEAVIATE_VERSION }}"  ]]; then
+                      echo "Error: Version is not equal to ${{ env.WEAVIATE_VERSION }}. Found $version"
+                      exit 1
+                  fi
+              done
